// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate() {
  return window['go']['main']['App']['ApplyUpdate']();
}

export function CancelAIChat(arg1) {
  return window['go']['main']['App']['CancelAIChat'](arg1);
}

export function ChatFolder() {
  return window['go']['main']['App']['ChatFolder']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearBackups() {
  return window['go']['main']['App']['ClearBackups']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function ExportDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportDialog'](arg1, arg2, arg3, arg4);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function FormatGo(arg1) {
  return window['go']['main']['App']['FormatGo'](arg1);
}

export function GetAIConfig() {
  return window['go']['main']['App']['GetAIConfig']();
}

export function GetStartupFiles() {
  return window['go']['main']['App']['GetStartupFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportTargets(arg1, arg2) {
  return window['go']['main']['App']['ImportTargets'](arg1, arg2);
}

export function IsDefaultMarkdownApp() {
  return window['go']['main']['App']['IsDefaultMarkdownApp']();
}

export function ListAIModels(arg1) {
  return window['go']['main']['App']['ListAIModels'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListChats() {
  return window['go']['main']['App']['ListChats']();
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function LoadChat(arg1) {
  return window['go']['main']['App']['LoadChat'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadState(arg1) {
  return window['go']['main']['App']['LoadState'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3, arg4);
}

export function OpenFolderDialog(arg1) {
  return window['go']['main']['App']['OpenFolderDialog'](arg1);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function PickChatBackup(arg1, arg2) {
  return window['go']['main']['App']['PickChatBackup'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveChat(arg1, arg2) {
  return window['go']['main']['App']['SaveChat'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveState(arg1, arg2) {
  return window['go']['main']['App']['SaveState'](arg1, arg2);
}

export function SearchFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFolder'](arg1, arg2, arg3);
}

export function SetChatFolder(arg1) {
  return window['go']['main']['App']['SetChatFolder'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetDocPath(arg1) {
  return window['go']['main']['App']['SetDocPath'](arg1);
}

export function SetTitleBarDark(arg1) {
  return window['go']['main']['App']['SetTitleBarDark'](arg1);
}

export function ShowDefaultAppDialog() {
  return window['go']['main']['App']['ShowDefaultAppDialog']();
}

export function StartAIChat(arg1, arg2) {
  return window['go']['main']['App']['StartAIChat'](arg1, arg2);
}

export function TestAIConnection(arg1) {
  return window['go']['main']['App']['TestAIConnection'](arg1);
}

export function WasUpdated() {
  return window['go']['main']['App']['WasUpdated']();
}

export function WriteBackup(arg1, arg2) {
  return window['go']['main']['App']['WriteBackup'](arg1, arg2);
}

export function WriteBase64File(arg1, arg2) {
  return window['go']['main']['App']['WriteBase64File'](arg1, arg2);
}
