// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate():Promise<void>;

export function CancelAIChat(arg1:string):Promise<void>;

export function ChatFolder():Promise<string>;

export function CheckForUpdate():Promise<main.UpdateCheck>;

export function ClearBackups():Promise<void>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteChat(arg1:string):Promise<void>;

export function ExportDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportPDF(arg1:string,arg2:string):Promise<void>;

export function FormatGo(arg1:string):Promise<string>;

export function GetAIConfig():Promise<main.AIConfigView>;

export function GetStartupFiles():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function ImportTargets(arg1:string,arg2:Array<string>):Promise<main.ImportTarget>;

export function IsDefaultMarkdownApp():Promise<boolean>;

export function ListAIModels(arg1:main.AISaveRequest):Promise<Array<string>>;

export function ListBackups():Promise<Array<string>>;

export function ListChats():Promise<Array<main.ChatMeta>>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function LoadChat(arg1:string):Promise<string>;

export function LoadSettings():Promise<main.Settings>;

export function LoadState(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function OpenFolderDialog(arg1:string):Promise<string>;

export function OpenWithDefaultApp(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function PickChatBackup(arg1:string,arg2:string):Promise<string>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<main.Document>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ResolvePath(arg1:string):Promise<string>;

export function SaveAIConfig(arg1:main.AISaveRequest):Promise<void>;

export function SaveChat(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SaveState(arg1:string,arg2:string):Promise<void>;

export function SearchFolder(arg1:string,arg2:main.SearchOptions,arg3:Array<string>):Promise<main.SearchResult>;

export function SetChatFolder(arg1:string):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetDocPath(arg1:string):Promise<void>;

export function SetTitleBarDark(arg1:boolean):Promise<void>;

export function ShowDefaultAppDialog():Promise<void>;

export function StartAIChat(arg1:string,arg2:Array<main.AIMessage>):Promise<void>;

export function TestAIConnection(arg1:main.AISaveRequest):Promise<main.AITestResult>;

export function WasUpdated():Promise<boolean>;

export function WriteBackup(arg1:string,arg2:string):Promise<void>;

export function WriteBase64File(arg1:string,arg2:string):Promise<void>;
